# Base configs
baseurl: "https://ryanpatrickthomas.photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by RPT"
subtitle: "Or world through my eyes"
author: "Ryan Patrick Thomas"
header:
 title: "Photography"
 subtitle: "by RPT"
footer:
 name: "Hola, Me Llamo Ryan"
 bio: "I live in the world and like to take pictures"
 
social_urls:
  facebook: "https://www.facebook.com/rypathom"
  twitter: "https://www.twitter.com/rpatrickthomas"
  instagram: "https://www.instagram.com/ryanpatrickthomas"
  linkedin: "https://www.https://www.linkedin.com/in/ryan-patrick-thomas-8bb49238/"
